### ISSUE TITLE
Not configurable header name problem

### ISSUE THREAD

**Issue by mhmtszr** [bkbnio/kompendium#113]
I need to give **X-UserEmail** as a header key, but I can't, I couldn't configure the name of the request headers it takes whatever I give for the variable name as the key, please add configuration for it.
For example:
@KompendiumParam(ParamType.HEADER) val email: String
If we would have param like "name" I think it would be great because we can't create X-UserEmail as a variable name.

**Comment by unredundant** [comment]
This is a good point! I wonder if it makes more sense to have dedicated annotations for each parameter type (query, path, header cookie) rather than a one size fits all annotation in V2 of this library.

For V1 I _think_ we can do this in a non breaking way by doing what you said and having an annotation parameter that defaults to an empty string.

**Comment by unredundant** [comment]
Actually... I believe this will work for ya 

```kotlin
data class HeaderNameTest(
  @KompendiumParam(type = ParamType.HEADER) val `X-UserEmail`: String
)
```

Kotlin is pretty flexible for naming conventions if you use backticks around the field name.  

Can you confirm if this works for what you need?

**Comment by mhmtszr** [comment]
It worked, thank you very much @unredundant you saved the day!
