### ISSUE TITLE
openapi client generator friendly

### ISSUE THREAD

**Issue by mareurs** [bkbnio/kompendium#176]
First of all I love how you wrote the project! Congrats!

I tried using Kompendium for a ktor microservice but I am having some issues with "org.openapi.generator" gradle plugin.

Because you are writing all the schemas inline (rather than referencing it from "components" tag) the models generated by the plugin have bad generated names (e.g. InlineResponse2001).
Maybe there is something that I am missing but please accept my 2 cents.

If you could:
1. Extract schemas in components
2. Name them appropriately, based on the class name
3. Reference the schemas from components using #ref
I think you would be the best project for generating Api Documentation for ktor :).

I'll fork your project, have a look at it and see if I can contribute.

In the meantime, keep up the good work! I'll follow you closely! :)

**Comment by unredundant** [comment]
Thanks for the kind words :) glad you like the project! 

This was actually how V1 was implemented, storing everything as referenced schemas. Unfortunately, as far as I can tell, you cannot have any kind of validation on reference schemas.  

So for v2, I decided to make them all inline.  However, there are a couple potential ways you can get around this.  

1. If you choose, you can annotate any class with `@Referenced`.  This will cause a reference type to be generated instead of the inline.  This would break any validation annotations, but this is more a limitation of OpenAPI than Kompendium as far as I'm aware.  
2. There is an `operationId` that was added in this PR #106 I've never actually used it but my understanding is that it gives you a way to override method names when generated by openapi generators.  Might not help you because I think you want to adjust actual data class names, but still good to know :) 

I was toying with the idea of adding an optional `name` parameter to `@Referenced` so that users could explicitly customize the reference name as well... do you think that would be helpful?

**Comment by unredundant** [comment]
Although... in playing with https://editor.swagger.io just now... it _does_ seem like you can add things like `minimum` and `maximum` to fields listed in the `#components/schema` array... so maybe we can go back to the approach where default is to have a reference.

**Comment by mareurs** [comment]
I tried annotating my data class with @Referenced but it still serializes it inline. Here is the class:

@Referenced
@Serializable
data class CommonVehicle(
    val vin: String,
    val vehicleNumber: String,
    val fbId: Long? = null,
    val dfId: Long? = null
)

**Comment by unredundant** [comment]
Ah you're right... annotating with referenced won't do anything at the moment due to a minor bug where the first level of a referenced class gets printed inline.  

Referenced was added to help prevent stack overflows for recursive objects.  

As for the serialization framework, it shouldn't matter :) Kompendium uses whichever content negotiator the api uses, and I've tested it with Jackson, Gson and Kotlinx and they're all supported. 

Good news tho is that I think we can move everything to referenced without breaking the constraint annotations that I added in V2.  

Not really sure why I thought the two couldn't coexist... guess I just got confused.

**Comment by unredundant** [comment]
Hey, above is a draft PR that would update Kompendium to take every complex object and hydrate the reference array with them.  Then, on generation of the schema, we just convert the type to it's reference slug rather than populating the array with the object reference in line.   

It is pretty much untested, and is going to break every test when I do :') but, i think this is a viable path forward. 

There are a couple of things I need to figure out 

1. All schemas need to be updated accordingly (array, map, etc.)
2. Recursive objects need to be supported

but neither of those should be _that_ bad.  @geirsagberg Just a heads up, I'm thinking about deprecating `@Referenced` and adding an annotation `@Recursive` since this PR would make every complex object a reference object.  It was a glorious week long lifespan for our `Referenced` annotation :)

**Comment by mareurs** [comment]
Thanks a bunch for the heads up! I will have a look at it and if it works I'll switch back to Kompendium. 
Will come back with feedback! Wish you the best of luck! :)
