### ISSUE TITLE
SwaggerUI on Ktor 2.x with the latest version of the lib

### ISSUE THREAD

**Issue by Marek00Malik** [bkbnio/kompendium#305]
**Describe the bug**
I"m trying to use the swagger UI available with this lib (but the version 2.3.5). When trying to start the app I'm getting the following issue:

```
    class io.bkbn.kompendium.swagger.SwaggerUI.Feature, unresolved supertypes: io.ktor.application.ApplicationFeature
Adding -Xextended-compiler-checks argument might provide additional information.
```
I think the issue is mainly related to the new Plugin mechanism used in Ktor 2.x. 
Are there plans for this plugin to be updated?

**Comment by unredundant** [comment]
Uhh yea you aren't gonna be able to cross cross major versions like that.  Kompendium 3 libs aren't backwards compatible with version 2. 

And version 3 has no swagger support, which is why I removed the module.  

The reason for this is that Swagger still does not support OpenAPI 3.1 which is the standard that Kompendium 3 uses in order to leverage the full JSON schema compatibility introduced in that spec.  

So, as soon as swagger supports OpenAPI 3.1, we can add this module back. Until then swagger is not usable unfortunately

**Comment by unredundant** [comment]
Closing this as there isn't really anything Kompendium can do but wait for swagger team

**Comment by Marek00Malik** [comment]
@unredundant Sorry for the late reply (I'm on holiday). Thanks for the replay, I noticed Swagger is not completed and there has been a ticket for it for a year.  
Thanks for this great tool, again!
