### ISSUE TITLE
Create github releases or deploy to maven central

### ISSUE THREAD

**Issue by dpnolte** [bkbnio/kompendium#37]
Currently the packages are created on Github. Although I really like github workflow, serving the packages on Github can  add a barrier to use it in other projects since it requires Github authentication ([github community issue](https://github.community/t/download-from-github-package-registry-without-authentication/14407)).

Currently I'm using Jitpack to retrieve it ([example build log](https://jitpack.io/com/github/lg-backbone/kompendium/30f02f8/build.log)). But at the moment no releases are created so only git commit hash can be used, which works but I rather use the version as tag that is mentioned in the change log.

I was wondering if something like the following would be possible:
- deploy to maven central 
   - I think that would be best as it easiest to integrate it on consuming projects.
   - This requires setting up an [Sonatype account ](https://central.sonatype.org/publish/publish-guide/)
- or, create releases on github when changelog has been changed on master 

Or do you have other ideas? Happy to help to moving this forward 🚀

**Comment by rgbrizzlehizzle** [comment]
Hmm I'm not opposed to pushing this to maven central, I really had hoped GitHub would move faster on this problem, because it's really nice having it fully integrated to Github, but the authentication for public repos is very annoying.  

Initial thought would be to keep the snapshots published to GitHub, and on release, push to MavenCentral.

Currently, I have a block in the root `build.gradle.kts`

```kotlin
version = run {
    val baseVersion =
      project.findProperty("project.version") ?: error("project.version must be set in gradle.properties")
    when ((project.findProperty("release") as? String)?.toBoolean()) {
      true -> baseVersion
      else -> "$baseVersion-SNAPSHOT"
    }
  }
```

that can be used to trigger a "release" build as opposed to a snapshot.  

So, we could adjust the publishing in a similar way.

Would require 

1. Creating sonatype account.
2. Creating a `release` GitHub action that would run when a release branch is created. 
3. Release would be very similar to the publish that runs on `main` except it would publish to MavenCentral and would set `release` property to `true`, causing the version to omit the `SNAPSHOT` 

Seems simple enough, any concerns?

**Comment by rgbrizzlehizzle** [comment]
tracking https://issues.sonatype.org/browse/OSSRH-67924

**Comment by dpnolte** [comment]
Awesome! Thank you for moving forward so fast 💯  
It would require further gradle configuration to publish to Maven Central. This gradle plugin could definitely help:
https://github.com/gradle-nexus/publish-plugin/

For your reference, I noticed that https://github.com/lg-backbone/OSSRH-67924 was not accessible for me.

**Comment by rgbrizzlehizzle** [comment]
> For your reference, I noticed that https://github.com/lg-backbone/OSSRH-67924 was not accessible for me.

Oh 😞 I made it private dang it

**Comment by rgbrizzlehizzle** [comment]
Hopefully you can see it now, I'll update the ticket as well if I need to

**Comment by rgbrizzlehizzle** [comment]
Sorry been busy, I will get to this ticket this weekend.  Officially moving this into the V1 milestone along with a couple small features

**Comment by rgbrizzlehizzle** [comment]
Hey again sorry on the delay here... This org is for a business I'm working on, so I was doing some logistical work in order to make it so I can get the Maven central name, the domain name, and the GitHub org name to all align.  Project is gonna remain open source and under MIT License of course but I'm going to be renaming the packages accordingly... hope that's ok 😃

**Comment by rgbrizzlehizzle** [comment]
I've moved this milestone to V2... not sure what the heck is going on, but I could get a snapshot up on nexus no problem but the release version failed every time.  So.... yea IDK just gonna stick to GitHub for now... I also accidentally wiped all the old package versions 😅 so now all that is left is 1.0.0 release version

**Comment by rgbrizzlehizzle** [comment]
ok some leads on the issue

1. Signing the package... there is a gradle signing plugin which can then allow you to sign the publication, see below
2. Sonatype appears to _require_ javadoc jar, see [here](https://central.sonatype.org/publish/requirements/#supply-javadoc-and-sources)

```kotlin
plugins {
    signing
}
signing {
    useGpgCmd()
    sign(publishing.publications["mavenJava"])
}
```
