### ISSUE TITLE
Mark field as deprecated

### ISSUE THREAD

**Issue by jorgebo10** [bkbnio/kompendium#406]
Is it possible to set a field as deprecated such as in the OpenApi specification?

**Comment by unredundant** [comment]
No but there should be, thanks for opening this!

It kinda falls in the same category as #289 which I would label "field metadata that is hard to attach cleanly without a million annotations". If you have any ideas I'd be glad to hear them :)

**Comment by unredundant** [comment]
Though now that I think about it, since Kotlin has a `Deprecated` annotation as part of the standard lib, it may make sense to leverage that.

**Comment by unredundant** [comment]
Still need to write tests, write docs, etc. but I am going to be including `deprecated` as an enrichment, which is the solution I have come up with for #407

This means it will not require an annotation, and can be added to a data class on a per method basis, rather than requiring on the data class itself. 

<img width="1472" alt="CleanShot 2023-01-04 at 18 19 59@2x" src="https://user-images.githubusercontent.com/5607577/210669551-052b2388-e5bc-4cd1-a883-34bf5580603b.png">

**Comment by unredundant** [comment]
This is going out now as part of release 3.10.0 🎉 

Here are some docs on how to get started https://bkbn.gitbook.io/kompendium/index-2/notarized_route#enrichment
