### ISSUE TITLE
Dependency of kompendium-core on logback

### ISSUE THREAD

**Issue by ospier** [bkbnio/kompendium#412]
In an application, we use kompendium to generate an OpenAPI spec for our REST API. And we use slf4j with log4j as backend for logging. After an upgrade from kompendium 2.3.5 to 3.9.0, we experienced the problem that slf4j found multiple bindings (log4j and logback) and it picked logback instead of log4j.

We solved the problem in our application by excluding the logback dependency (like suggested in the slf4j docs: https://www.slf4j.org/codes.html#multiple_bindings) in our gradle build file:

```
    implementation("io.bkbn:kompendium-core") {
        exclude(group = "ch.qos.logback")
    }
```

However, I would expect a library like kompendium to not add transitive dependencies to a specific logging provider. In fact, if I'm not mistaken, kompendium (or at least kompendium-core) does not even use logback (or any logging, for that matter). So maybe this dependency can simply be removed?

**Comment by unredundant** [comment]
huh... not clear to me why this happens since logback was defined as an implementation dependency, and not an api dependency, but gradle dep management is weird.  

Anyway, I think you're right in that Kompendium doesn't need logback since we don't do any logging, so I removed it in the PR above.  Will roll out a patch release in a minute, should be `3.11.1`
