### ISSUE TITLE
TypeEnrichment for (nested) collection types

### ISSUE THREAD

**Issue by benedikt-wueller** [bkbnio/kompendium#541]
In the following scenario, is there any way to enrich the inner `Item` properties?
 
```kotlin
data class Item(val foo: String, val bar: Int)
```
```kotlin
responseType<List<Item>>(TypeEnrichment.invoke("enrichment_id") {
  // how to enrich Item properties?
})
```

Maybe I'm missing something but to me it looks like this is not possible using the `TypeEnrichment` and `PropertyEnrichment` helpers as the nesting functionality does not work for collections (as there is no property within the `List` type to attach the `TypeEnrichment` for the `Item` to).

I currently assume the only workaround for now would be to provide a custom `JsonSchema` in the `customTypes` of the `NotarizedApplication` plugin config. Is this correct?

**Comment by unredundant** [comment]
oh... yea this is a great point, that probably won't work.  I saw that a ktor 3.0 release beta was just announced, so, will likely try to coordinate the 4.0 release of kompendium with that release.  This should definitely be added before we cut the official 4.0 release.

Thanks for opening this 🙏

**Comment by unredundant** [comment]
This turned out to be a bit of a tricky problem due to my original implementation being... not so great... right now, I'm leaning towards solving this with an extra layer of inheritance for the enrichment lib... so enriching a top-level list would look something like the following 

```kt
requestType(
  enrichment = CollectionEnrichment<List<TestSimpleRequest>>("blah-blah") {
    itemEnrichment = ObjectEnrichment("simple") {
      TestSimpleRequest::a {
        description = "A simple description"
      }
      TestSimpleRequest::b {
        deprecated = true
      }
    }
  }
)
```

So, this would definitely need to be a breaking change pushed in v4, because then, `TypeEnrichment<T>` becomes a sealed interface, and what is currently defined as `TypeEnrichment` instead becomes `ObjectEnrichment<T> : TypeEnrichment<T>`

**Comment by benedikt-wueller** [comment]
Thank you so much for the work you are putting into this project! I'll give the new version a try soon.
