### ISSUE TITLE
Sonatype integration broken

### ISSUE THREAD

**Issue by brizzbuzz** [bkbnio/kompendium#568]
https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/

:( maybe cuz of this?

**Comment by n3ziniuka5** [comment]
It's a shame that publishing to maven central is broken, because to pull an artifact from GitHub packages you must authenticate, so that needs to be done by every team member and also CI.

**Comment by brizzbuzz** [comment]
Just FYI... This has led to a state where the docs are currently published for the 4.0 release, but the release is not available beyond pulling it from GitHub... hopefully I'll find some time soon to fix whatever broke with maven publishing, but till then docs will be unfortunately not matching with the actual available code :(

**Comment by brizzbuzz** [comment]
Something is completely broken w/ the sonatype ecosystem.  I logged into the JIRA system they maintain to try to open a ticket, and got a message that permissions to create new tickets have been turned off.  

They also seem to be in the progress of some large scale migration, not sure when that will be completed, but, unless I can somehow get in contact with support, then this project will likely just be completely blocked / broken until they finish up whatever migrations have caused all these problems. 

It's really dejecting to be stuck like this, but I'm not sure what more can be done.  

In the mean time, I'll likely roll back the docs to match with the latest 3.X release, and all the changes that were set for 4.0 and beyond will likely just be stuck in limbo until all of this crap is sorted out

**Comment by rocketraman** [comment]
Did you get this email from them?

Greetings Maven Central Publisher,

We are reaching out to you because you are registered as a publisher with Maven Central’s [oss.sonatype.org](http://oss.sonatype.org/) or [s01.oss.sonatype.org](http://s01.oss.sonatype.org/) services. Although there are no immediate changes to how you publish, we want to inform you of a number of upcoming changes to your account. Currently, you manage your account credentials through [issues.sonatype.org](http://issues.sonatype.org/). On Tuesday the 12th of March, we are moving account management to a temporary service located at [https://account.oss.sonatype.org/realms/central-ossrh/account/](https://u21795309.ct.sendgrid.net/ls/click?upn=u001.cdbupahfLeeV0JrmnGgqhmrkSpaJs-2FAXk1UxmFQyoqkxghtD-2BsbQvbtncphSXH6Jx1NTrruOQ5KGQt9XimpaQQd2ELcBR78XdWSabPCyAws-3DM0HN_3m7LCSkFzXz1kjAcn9HrBR3e3Wnnt60namUzW7djfOBuRMwSIuZXVWtJNCWddKItFR653ZLoJfzUm0de6DdtsJufsy2znloxECRFtJe8AHdHI0Y-2B1acyKlDPtt0yz2flaiWkdIecwqfDAhuTF2ydVR95Q7sGCZC5bi0UjGQBfWLIDUG2n8Yf3B0pQz1LaNmxwkPhj-2FJHoQJM31odvbqy-2B3kAghLyVLEEy9BN9wOuaWBrJZ9KxVZyLn1MFAQBMZZC4tDcwp-2BzKAWJyMHtNnvMgjyEkKk-2BW5ZUbZrf5KA8ADTdCQfcJtsqahy-2Bkd3ODCHY7bu7sdtdNt5YVM3NjbgFqTRejQa7X-2FqGmVwrJvFc-2Fnd-2B8hVq3z7MW4HmCDs5gLhWDEzBDEO9BVVHlbkTu5tyI2ZFlutqWxM-2BC8VNp2V8-2FM2jKQTbxPfzec76trd9c5j-2FX1nBZw94OP10CBxZSN1MRgEFu2YWTwEbs6nl58A-2BqdFb-2BI-2BXSklxDftL4F0182ZXCwgLFjAclBK2AVd90LxWX6sv1Zp0yev3M3gd0enq3qrhI0FGKlQRnDSf1NUPTDwp-2BgbebDT2N23zpUDR4CMiAtTxsS3viwErH9p8KHjOieyPfxmiShSUaLb8v6iGjgLNjMEz-2FWnf0MQWAASZJL9Zic9Zz-2FXc0uG4VpQRptHh0U8-2F0ju7QD2CWPXa96ovIhKk9OW4-2F5BrStW4K9TNYXmEq1t2l-2FpVOi3rVX-2FL38wZwG3K4K6S4TL6A0tjIJPWr6Oto7CcSr-2FR0rVcv-2BzrfIurQ3o7JX-2BA7LYSO3v5V8tyHaUvk6ATQINQ7n9dXTEo69yA-2BZXIscuRYMRj-2F01ElI9YH-2B-2B7fUJBd-2FizrQo-2FjuTl92ERGbDx-2BoORsTQ0vB4-2BVF3R75NsXfmxstzfjKSZH6gxAFlpPFrJIZjZYtLHL1CuK8mUPUlGF9n8kEiTyKK6tPBstABQ4GYTJaG8oXruPUK9-2FhrYdU9XZD3nRaeTiKBdAvmHg9Wfc0q1jQghUoQXqqN8KpbK-2FE5a0TcFgJLujKc7MA-3D-3D). This should hopefully involve minimal disruption for our publishers. You will still use the same username and password to log in to the OSSRH instance, and should only need to interact with the new account management service when you wish to change or reset your account credentials.

Also, you will likely see information directed at new OSSRH publishers registering via [central.sonatype.com](http://central.sonatype.com/) (documented here -- https://central.sonatype.org/register/legacy/). While this does not impact you at the moment, you should be aware that we are moving account management to a unified system across the Central Publishing Portal and OSSRH. We will communicate again before that takes place, to ensure that our users have a clear understanding of where and how they will be able to manage their accounts.

You may also have been impacted by the retirement of [issues.sonatype.org](http://issues.sonatype.org/) which you previously used for signing up for new namespaces and getting publishing support. We have transitioned to using the same workflow system used for our paid products. To generate a ticket, you can email [central-support@sonatype.com](mailto:central-support@sonatype.com). We acknowledge that, in doing so, you have lost some of the self-service functionality for requesting and being granted publisher access to new namespaces. We are working on restoring that functionality on [central.sonatype.com](http://central.sonatype.com/). The migration to a unified account management system we mentioned previously enables us to build integrations between the two services later in the year, such as displaying a user’s complete list 
of registered namespaces and allowing self-service migration to the Publisher Portal.

**Comment by rocketraman** [comment]
> I don't personally use this library / Kotlin any more :(

Oh, that's too bad. You seem to have done a pretty amazing job with this lib. Hopefully you find some way to move forward with it, or someone to take it over.

**Comment by brizzbuzz** [comment]
Update, I've reached out to the central team via email, so will wait on their response.  It looks like they've done a complete rehaul of their identity platform, and my credentials seem to have gotten messed up in the process.  

So I'm going to need them to assign the bkbn namespace to my new identity, and then I should be able to publish :crossed_fingers:

**Comment by brizzbuzz** [comment]
alright.... this is mostly fixed.... it doesn't work on github actions for some reason, and was so absurdly frustrating that if this ever breaks again I'm archiving the project lmao... but I was able to successfully publish v4 from my laptop.  

v `4.0.0` was sort of an accidential push, I thought i had set a test suffix to the version but somehow that got reverted... recommend using `4.0.1`
