### ISSUE TITLE
Add support for multiple operations of the same type

### ISSUE THREAD

**Issue by oSumAtrIX** [bkbnio/kompendium#613]
Ktor allows the following:

```kt
get { }
get("path") { }
```

Kompendium only allows to notarize the get operation, and only one.
The current workaround is to wrap in a route:

```kt
get { }
route("path") {
 get { }
}
```

**Comment by brizzbuzz** [comment]
can you provide a more concrete proposal of what you would want the former to look like?

Asking because the entire purpose of route level plugins is to allow for each route to be configurable.

its totally fine to want to define a route the way you do in the first example, but of course you are giving up some control as to the fine grained nature of controlling the instantiation of said route

**Comment by oSumAtrIX** [comment]
I have a route:

```kt
route("/users/{user]/")
 get { }
 get("id")
}
```

but I can't properly notarize both get operations.
