### ISSUE TITLE
Need version 4 for sealed classed

### ISSUE THREAD

**Issue by m-umar-bilal** [bkbnio/kompendium#625]
**Describe the bug**
Hi, 

Need version 4 for sealed classes. Any chance you would be able to just push release 4 last time?

Thanks so much for this great library

**Comment by brizzbuzz** [comment]
for many moons publishing has been broken due to the maven team giving maven central a refresh, but i finally did get my new account properly set up.  

so hopefully will be able to publish V4 soon, tho can't promise an exact timeline. 

glad you have found Kompendium useful :) 

i don't really get to write much Kotlin any more and miss it a lot

**Comment by m-umar-bilal** [comment]
Thanks so much
