### ISSUE TITLE
OAuth authentication not supported

### ISSUE THREAD

**Issue by LandryNorris** [bkbnio/kompendium#93]
This library currently only supports Basic and JWT, and will crash when provided with a route inside of an authenticate block using oauth. (No handler has been registered for (authenticate auth-oauth-google)). A workaround for projects using OAuth would be helpful.

**Comment by rgbrizzlehizzle** [comment]
Don't know if there is any workaround that is going to work.  It just needs to be implemented. 

I took a peek at the oauth spec for OpenAPI, it doesn't seem to crazy.  Would be awesome if you'd like to take a crack at adding that to the auth module ;)

**Comment by unredundant** [comment]
Unfortunately, this is going to have to wait until V2, as there are fundamental problems with the models that I made at the moment.  It _technically_ wouldn't be a breaking change because this functionality doesn't exist at all, but due to the large shift in how auth will get parsed, I'm going to be safe and mark it as a v2 target.
