### ISSUE TITLE
Optional fields without being null

### ISSUE THREAD

**Issue by pakerfeldt** [bkbnio/kompendium#98]
The only way I've found kompendium to mark a field optional is to have it nullable. However, one could in theory also use non-null fields with default values in data classes. When I do this they show up as required fields in Swagger. Is there a way to have them show as optional without marking them nullable?

**Comment by rgbrizzlehizzle** [comment]
Hmmmm off the top of my head I don't think so.  I'm not actually sure I ever even coded up the ability to mark request body fields as nullable vs not (in a request body... I believe for path/query parameters the functionality is there).  

Will add this to my list of bugs to look into :) I've been super busy recently, so if this is something you'd like to take a stab at fixing that would be awesome!

**Comment by rgbrizzlehizzle** [comment]
IIRC in OpenAPI, all request bodies are considered optional by default... so most likely this would need to maintain a list of _required_ fields rather than optional ones, and then mark those explicitly as required.  Which is good, because I'm not sure that things like default values are going to be available via reflection.

**Comment by unredundant** [comment]
This will be fixed in V2 :) As mentioned above, values are considered optional in OpenAPI by default.  But now, Kompendium will show a field as "required" when there is no default value assigned to the parameter. 

I have opened a separate issue #130 to track trying to _actually_ display default values, but this requires some reallly ugly reflection magic.  I do a simpler version of it to get default parameters to work, but parameters are much simpler to scan via reflection that full complex objects.
